[workspace]
members = [
	"k8s_wasi",
    "examples/my-authenticator",
    "examples/my-authorizer",
    "examples/my-validator",
    "examples/my-mutator",
    "examples/magic-authenticator",
    "examples/magic-authorizer",
    "examples/magic-validator",
    "examples/magic-mutator",
]