[package]
name = "magic-authorizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
k8s_wasi = { path = "../../k8s_wasi" }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }