[package]
name = "k8s_wasi"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
base64 = "0.13.0"